import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ForumNavbar from "@/components/ForumNavbar";
import CustomScrollbar from "@/components/CustomScrollbar";
import ReactLenis from "lenis/react";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
      <ReactLenis
                    root
                    options={{
                      lerp: 0.16,
                      wheelMultiplier: 1,
                      smoothWheel: true,
                      orientation: "vertical",
                      gestureOrientation: "vertical",
                      infinite: false,
                      syncTouch: true,
                    }}
                  >
        <CustomScrollbar />
        <ForumNavbar />
        {children}
        </ReactLenis>
      </body>
    </html>
  );
}
